### ISSUE TITLE
There is no `sidekictl` in sidekiq 6

### ISSUE THREAD

**Issue by dastra-mak** [makandra/makandra_sidekiq#1]
I upgraded gems and found out that my deployment is not working any more with sidekiq 6:

```
Caused by:
SSHKit::Command::Failed: rake exit status: 1
rake stdout: Stopping Sidekiq...
rake stderr: rake aborted!
["sidekiqctl", "stop", "/var/www/xxx/releases/20191021193051/tmp/pids/sidekiq.pid"] failed with message: bundler: failed to load command: sidekiqctl (/var/www/xxx/shared/bundle/ruby/2.6.0/bin/sidekiqctl)
Gem::Exception: can't find executable sidekiqctl for gem sidekiq
  /home/deploy-xxx/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
  /home/deploy-xxx/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
  /var/www/xxx/shared/bundle/ruby/2.6.0/bin/sidekiqctl:23:in `<top (required)>'
/var/www/xxx/shared/bundle/ruby/2.6.0/gems/makandra_sidekiq-0.1.4/lib/makandra_sidekiq/sidekiq_control.rb:157:in `bundle_exec'
/var/www/xxx/shared/bundle/ruby/2.6.0/gems/makandra_sidekiq-0.1.4/lib/makandra_sidekiq/sidekiq_control.rb:98:in `run_sidekiqctl'
/var/www/xxx/shared/bundle/ruby/2.6.0/gems/makandra_sidekiq-0.1.4/lib/makandra_sidekiq/sidekiq_control.rb:29:in `stop'
```

It looks like `sidekiqctl` was removed in sidekiq 6 (https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md).

I think a short-term fix would be to depend on sidekiq < 6. For a long-term solution we should not use the sidekiqctl binary.

**Comment by codener** [comment]
Since we're currently not using Sidekiq 6, nor intending to upgrade, we'll solve this by depending on Sidekiq < 6. 

A solution for Sidekiq 6+ will only be developed once we'll be using it.
